// Builds data/timing.js (word-level cues on the tightened timeline) from Descript's SRT and cuts.json.
// Descript's SRT gives phrase timings only, so words are spread across each phrase by length.
// When word-level timestamps are available (whisper / Descript word export), replace spreadWords().
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const srt = fs.readFileSync(path.join(root, "data/edits.srt"), "utf8");
const cuts = JSON.parse(fs.readFileSync(path.join(root, "data/cuts.json"), "utf8"));

const toSec = (ts) => { const [h, m, s] = ts.replace(",", ".").split(":"); return +h * 3600 + +m * 60 + +s; };
const phrases = srt.trim().split(/\n\s*\n/).map((block) => {
  const lines = block.split("\n");
  const [a, b] = lines[1].split(" --> ").map(toSec);
  return { start: a, end: b, text: lines.slice(2).join(" ").trim() };
});

function spreadWords(p) {
  const words = p.text.split(/\s+/);
  const weight = (w) => w.replace(/[^\w:']/g, "").length + 2 + (/[,.?!]$/.test(w) ? 2 : 0);
  const total = words.reduce((n, w) => n + weight(w), 0);
  let t = p.start;
  return words.map((w) => {
    const d = ((p.end - p.start) * weight(w)) / total;
    const out = { w, s: t, e: t + d * 0.92 };
    t += d;
    return out;
  });
}

// Map a source time onto the tightened timeline. Cut points snap to the 30fps grid (same as tools/prep-footage.sh).
const snap = (x) => Math.round(x * 30) / 30;
const keep = cuts.keep.map(([a, b]) => [snap(a), snap(b)]);
const ranges = [];
let acc = 0;
for (const [a, b] of keep) { ranges.push({ a, b, off: acc }); acc += b - a; }
function mapT(t) {
  for (const r of ranges) if (t >= r.a && t <= r.b) return r.off + (t - r.a);
  // In a removed gap: snap to the start of the next kept range.
  const next = ranges.find((r) => r.a > t);
  return next ? next.off : acc;
}

const r3 = (n) => Math.round(n * 1000) / 1000;
const words = phrases.flatMap(spreadWords).map((x) => ({ w: x.w, s: r3(mapT(x.s)), e: r3(mapT(x.e)) }));
const out = { duration: r3(acc), fps: 30, keep: keep.map(([a, b]) => [r3(a), r3(b)]), words };
fs.writeFileSync(path.join(root, "data/timing.js"), `// Generated by tools/timing.mjs. Do not edit by hand.\nwindow.TIMING = ${JSON.stringify(out, null, 1)};\n`);
console.log(`duration ${out.duration}s, ${words.length} words`);
